name: 百度贴吧

on:
  workflow_dispatch:
  schedule:
    #- cron: '0 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: start
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/wunian588/HAOYANGMAO.git ~/HAOYANGMAO
      - name: Use baidutieba.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/HAOYANGMAO
          git checkout main
          npm install
      - name: '运行 【百度贴吧】'
        run: |
          cd ~/HAOYANGMAO/The.Flash/The.Flash/
          node baidutieba.js
        env:
          TZ: Asia/shanghai
